import 'package:flutter/material.dart';

// Only Material icons are supported, so IconType enum is no longer needed.
class CustomIcon {
  final IconData materialIconData; // Stores Material IconData directly
  final Color? color; // Optional color for Material icons

  const CustomIcon.material(this.materialIconData, {this.color});

  // Getter for materialIcon is simplified as it's the only type
  IconData get materialIcon => materialIconData;

  // toWidget method now only handles Material Icons
  Widget toWidget({double size = 30, Color? defaultColor}) {
    return Icon(materialIconData, size: size, color: color ?? defaultColor);
  }

  // Method to convert CustomIcon to a savable string (only Material icons)
  String toSavableString() {
    return 'material:${materialIconData.codePoint}${color != null ? '::${color!.value.toRadixString(16).toUpperCase()}' : ''}';
  }

  // Static method to create CustomIcon from a savable string (only Material icons)
  static CustomIcon fromSavableString(String savableString) {
    if (savableString.startsWith('material:')) {
      final parts = savableString.substring('material:'.length).split('::');
      final codePoint = int.parse(parts[0]);
      Color? color;
      if (parts.length > 1) {
        color = Color(int.parse(parts[1], radix: 16));
      }
      return CustomIcon.material(IconData(codePoint, fontFamily: 'MaterialIcons'), color: color);
    }
    // Fallback for any unparseable string, e.g., a default icon
    return const CustomIcon.material(Icons.error); // Keep fallback for safety
  }

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CustomIcon &&
          runtimeType == other.runtimeType &&
          materialIconData == other.materialIconData &&
          color == other.color;

  @override
  int get hashCode => materialIconData.hashCode ^ color.hashCode;

  CustomIcon copyWith({
    IconData? materialIconData,
    Color? color,
  }) {
    return CustomIcon.material(
      materialIconData ?? this.materialIconData,
      color: color ?? this.color,
    );
  }
}

// List of available material icons (simplified as "colorful" aspect is handled by color picker)
final List<CustomIcon> availableMaterialIcons = [
  // Core Habits
  const CustomIcon.material(Icons.directions_run),
  const CustomIcon.material(Icons.book),
  const CustomIcon.material(Icons.water_drop),
  const CustomIcon.material(Icons.fitness_center),
  const CustomIcon.material(Icons.self_improvement),
  const CustomIcon.material(Icons.bedtime),
  const CustomIcon.material(Icons.fastfood),
  const CustomIcon.material(Icons.local_library),
  const CustomIcon.material(Icons.work),
  const CustomIcon.material(Icons.music_note),
  const CustomIcon.material(Icons.people),
  const CustomIcon.material(Icons.lightbulb),
  const CustomIcon.material(Icons.brush),
  const CustomIcon.material(Icons.code),
  const CustomIcon.material(Icons.camera_alt),
  const CustomIcon.material(Icons.shopping_cart),
  const CustomIcon.material(Icons.pets),
  const CustomIcon.material(Icons.videogame_asset),
  const CustomIcon.material(Icons.local_cafe),
  const CustomIcon.material(Icons.directions_bike),
  const CustomIcon.material(Icons.spa),
  const CustomIcon.material(Icons.school),
  const CustomIcon.material(Icons.palette),
  const CustomIcon.material(Icons.flight),
  const CustomIcon.material(Icons.money),
  const CustomIcon.material(Icons.healing),
  const CustomIcon.material(Icons.sentiment_satisfied),
  const CustomIcon.material(Icons.star),
  const CustomIcon.material(Icons.favorite),
  const CustomIcon.material(Icons.home),
  const CustomIcon.material(Icons.business),
  const CustomIcon.material(Icons.build),
  const CustomIcon.material(Icons.cloud),
  const CustomIcon.material(Icons.computer),
  const CustomIcon.material(Icons.dashboard),
  const CustomIcon.material(Icons.eco),
  const CustomIcon.material(Icons.edit),
  const CustomIcon.material(Icons.email),
  const CustomIcon.material(Icons.event),
  const CustomIcon.material(Icons.extension),
  const CustomIcon.material(Icons.face),
  const CustomIcon.material(Icons.flash_on),
  const CustomIcon.material(Icons.folder),
  const CustomIcon.material(Icons.group),
  const CustomIcon.material(Icons.headset),
  const CustomIcon.material(Icons.help),
  const CustomIcon.material(Icons.history),
  const CustomIcon.material(Icons.hourglass_empty),
  const CustomIcon.material(Icons.insert_chart),
  const CustomIcon.material(Icons.keyboard),
  const CustomIcon.material(Icons.language),
  const CustomIcon.material(Icons.layers),
  const CustomIcon.material(Icons.location_on),
  const CustomIcon.material(Icons.lock),
  const CustomIcon.material(Icons.mail),
  const CustomIcon.material(Icons.map),
  const CustomIcon.material(Icons.message),
  const CustomIcon.material(Icons.mic),
  const CustomIcon.material(Icons.mood),
  const CustomIcon.material(Icons.notifications),
  const CustomIcon.material(Icons.offline_bolt),
  const CustomIcon.material(Icons.pan_tool),
  const CustomIcon.material(Icons.phone),
  const CustomIcon.material(Icons.photo),
  const CustomIcon.material(Icons.pie_chart),
  const CustomIcon.material(Icons.place),
  const CustomIcon.material(Icons.public),
  const CustomIcon.material(Icons.query_builder),
  const CustomIcon.material(Icons.radio),
  const CustomIcon.material(Icons.receipt),
  const CustomIcon.material(Icons.redeem),
  const CustomIcon.material(Icons.refresh),
  const CustomIcon.material(Icons.report),
  const CustomIcon.material(Icons.restaurant),
  const CustomIcon.material(Icons.room),
  const CustomIcon.material(Icons.rss_feed),
  const CustomIcon.material(Icons.save),
  const CustomIcon.material(Icons.schedule),
  const CustomIcon.material(Icons.search),
  const CustomIcon.material(Icons.security),
  const CustomIcon.material(Icons.send),
  const CustomIcon.material(Icons.settings),
  const CustomIcon.material(Icons.share),
  const CustomIcon.material(Icons.shield),
  const CustomIcon.material(Icons.shopping_bag),
  const CustomIcon.material(Icons.show_chart),
  const CustomIcon.material(Icons.star_border),
  const CustomIcon.material(Icons.store),
  const CustomIcon.material(Icons.sunny),
  const CustomIcon.material(Icons.support),
  const CustomIcon.material(Icons.sync),
  const CustomIcon.material(Icons.tag),
  const CustomIcon.material(Icons.task),
  const CustomIcon.material(Icons.text_fields),
  const CustomIcon.material(Icons.thumb_up),
  const CustomIcon.material(Icons.timer),
  const CustomIcon.material(Icons.today),
  const CustomIcon.material(Icons.toggle_on),
  const CustomIcon.material(Icons.toll),
  const CustomIcon.material(Icons.topic),
  const CustomIcon.material(Icons.touch_app),
  const CustomIcon.material(Icons.track_changes),
  const CustomIcon.material(Icons.traffic),
  const CustomIcon.material(Icons.translate),
  const CustomIcon.material(Icons.trending_up),
  const CustomIcon.material(Icons.tune),
  const CustomIcon.material(Icons.umbrella),
  const CustomIcon.material(Icons.undo),
  const CustomIcon.material(Icons.unfold_less),
  const CustomIcon.material(Icons.update),
  const CustomIcon.material(Icons.upload_file),
  const CustomIcon.material(Icons.verified),
  const CustomIcon.material(Icons.videocam),
  const CustomIcon.material(Icons.visibility),
  const CustomIcon.material(Icons.volume_up),
  const CustomIcon.material(Icons.wallet),
  const CustomIcon.material(Icons.watch),
  const CustomIcon.material(Icons.waves),
  const CustomIcon.material(Icons.wb_sunny),
  const CustomIcon.material(Icons.wifi),
  const CustomIcon.material(Icons.widgets),
  const CustomIcon.material(Icons.wine_bar),
  const CustomIcon.material(Icons.workspaces),
  const CustomIcon.material(Icons.wrap_text),
  const CustomIcon.material(Icons.wysiwyg),
  const CustomIcon.material(Icons.youtube_searched_for),
  const CustomIcon.material(Icons.zoom_in),
  const CustomIcon.material(Icons.zoom_out),
  // New icons for navigation
  const CustomIcon.material(Icons.check_box_outlined),
  const CustomIcon.material(Icons.history_toggle_off_outlined),
  const CustomIcon.material(Icons.settings_outlined),
  // Commonly Used Icons
  const CustomIcon.material(Icons.home),
  const CustomIcon.material(Icons.add),
  const CustomIcon.material(Icons.settings),
  const CustomIcon.material(Icons.check_circle),
  const CustomIcon.material(Icons.edit),
  const CustomIcon.material(Icons.delete),
  const CustomIcon.material(Icons.arrow_back),
  const CustomIcon.material(Icons.menu),
  const CustomIcon.material(Icons.search),
  const CustomIcon.material(Icons.logout),
  // Smart UI Enhancer Icons
  const CustomIcon.material(Icons.star),
  const CustomIcon.material(Icons.favorite),
  const CustomIcon.material(Icons.calendar_today),
  const CustomIcon.material(Icons.alarm),
  const CustomIcon.material(Icons.dark_mode),
  const CustomIcon.material(Icons.emoji_events),
  const CustomIcon.material(Icons.auto_graph),
  const CustomIcon.material(Icons.bolt),
  const CustomIcon.material(Icons.fitness_center),
  const CustomIcon.material(Icons.nightlight_round),
  // Additional Material Icons for variety
  const CustomIcon.material(Icons.accessibility_new),
  const CustomIcon.material(Icons.account_balance),
  const CustomIcon.material(Icons.agriculture),
  const CustomIcon.material(Icons.airplanemode_active),
  const CustomIcon.material(Icons.anchor),
  const CustomIcon.material(Icons.architecture),
  const CustomIcon.material(Icons.assessment),
  const CustomIcon.material(Icons.attractions),
  const CustomIcon.material(Icons.audiotrack),
  const CustomIcon.material(Icons.auto_stories),
  const CustomIcon.material(Icons.bakery_dining),
  const CustomIcon.material(Icons.bar_chart),
  const CustomIcon.material(Icons.beach_access),
  const CustomIcon.material(Icons.biotech),
  const CustomIcon.material(Icons.blender),
  const CustomIcon.material(Icons.bookmark),
  const CustomIcon.material(Icons.brightness_medium),
  const CustomIcon.material(Icons.campaign),
  const CustomIcon.material(Icons.celebration),
  const CustomIcon.material(Icons.chat),
  const CustomIcon.material(Icons.clean_hands),
  const CustomIcon.material(Icons.construction),
  const CustomIcon.material(Icons.cookie),
  const CustomIcon.material(Icons.create),
  const CustomIcon.material(Icons.credit_card),
  const CustomIcon.material(Icons.deck),
  const CustomIcon.material(Icons.delivery_dining),
  const CustomIcon.material(Icons.directions_car),
  const CustomIcon.material(Icons.directions_walk),
  const CustomIcon.material(Icons.diversity_3),
  const CustomIcon.material(Icons.downhill_skiing),
  const CustomIcon.material(Icons.dry_cleaning),
  const CustomIcon.material(Icons.egg),
  const CustomIcon.material(Icons.emoji_food_beverage),
  const CustomIcon.material(Icons.engineering),
  const CustomIcon.material(Icons.escalator_warning),
  const CustomIcon.material(Icons.ev_station),
  const CustomIcon.material(Icons.explore),
  const CustomIcon.material(Icons.face_retouching_natural),
  const CustomIcon.material(Icons.family_restroom),
  const CustomIcon.material(Icons.festival),
  const CustomIcon.material(Icons.filter_vintage),
  const CustomIcon.material(Icons.fireplace),
  const CustomIcon.material(Icons.fit_screen),
  const CustomIcon.material(Icons.flatware),
  const CustomIcon.material(Icons.forest),
  const CustomIcon.material(Icons.free_breakfast),
  const CustomIcon.material(Icons.front_hand),
  const CustomIcon.material(Icons.gamepad),
  const CustomIcon.material(Icons.gavel),
  const CustomIcon.material(Icons.gesture),
  const CustomIcon.material(Icons.golf_course),
  const CustomIcon.material(Icons.handshake),
  const CustomIcon.material(Icons.hardware),
  const CustomIcon.material(Icons.hiking),
  const CustomIcon.material(Icons.hot_tub),
  const CustomIcon.material(Icons.icecream),
  const CustomIcon.material(Icons.kayaking),
  const CustomIcon.material(Icons.king_bed),
  const CustomIcon.material(Icons.kitesurfing),
  const CustomIcon.material(Icons.local_bar),
  const CustomIcon.material(Icons.local_gas_station),
  const CustomIcon.material(Icons.local_hospital),
  const CustomIcon.material(Icons.local_laundry_service),
  const CustomIcon.material(Icons.local_parking),
  const CustomIcon.material(Icons.local_pharmacy),
  const CustomIcon.material(Icons.local_shipping),
  const CustomIcon.material(Icons.luggage),
  const CustomIcon.material(Icons.masks),
  const CustomIcon.material(Icons.medical_services),
  const CustomIcon.material(Icons.menu_book),
  const CustomIcon.material(Icons.military_tech),
  const CustomIcon.material(Icons.movie),
  const CustomIcon.material(Icons.museum),
  const CustomIcon.material(Icons.nature),
  const CustomIcon.material(Icons.nordic_walking),
  const CustomIcon.material(Icons.park),
  const CustomIcon.material(Icons.pedal_bike),
  const CustomIcon.material(Icons.personal_injury),
  const CustomIcon.material(Icons.piano),
  const CustomIcon.material(Icons.pool),
  const CustomIcon.material(Icons.ramen_dining),
  const CustomIcon.material(Icons.recycling),
  const CustomIcon.material(Icons.rowing),
  const CustomIcon.material(Icons.safety_divider),
  const CustomIcon.material(Icons.science),
  const CustomIcon.material(Icons.skateboarding),
  const CustomIcon.material(Icons.sports_baseball),
  const CustomIcon.material(Icons.sports_basketball),
  const CustomIcon.material(Icons.sports_cricket),
  const CustomIcon.material(Icons.sports_esports),
  const CustomIcon.material(Icons.sports_football),
  const CustomIcon.material(Icons.sports_golf),
  const CustomIcon.material(Icons.sports_hockey),
  const CustomIcon.material(Icons.sports_martial_arts),
  const CustomIcon.material(Icons.sports_motorsports),
  const CustomIcon.material(Icons.sports_rugby),
  const CustomIcon.material(Icons.sports_soccer),
  const CustomIcon.material(Icons.sports_tennis),
  const CustomIcon.material(Icons.sports_volleyball),
  const CustomIcon.material(Icons.surfing),
  const CustomIcon.material(Icons.theater_comedy),
  const CustomIcon.material(Icons.thermostat),
  const CustomIcon.material(Icons.toys),
  const CustomIcon.material(Icons.tram),
  const CustomIcon.material(Icons.travel_explore),
  const CustomIcon.material(Icons.two_wheeler),
  const CustomIcon.material(Icons.volunteer_activism),
  const CustomIcon.material(Icons.wallet_giftcard),
  const CustomIcon.material(Icons.wash),
  const CustomIcon.material(Icons.waves),
  const CustomIcon.material(Icons.wb_cloudy),
  const CustomIcon.material(Icons.weekend),
  const CustomIcon.material(Icons.wheelchair_pickup),
  const CustomIcon.material(Icons.wine_bar),
  const CustomIcon.material(Icons.workspace_premium),
  const CustomIcon.material(Icons.yard),
];
